version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-loopback-video
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      ##- rabbitmq_micro-video COMPOSE DO RABBITMQ MOVIDO PARA ESTE ARQUIVO
    depends_on:
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: micro-elastic-video
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network
    depends_on:
      - rabbitmq

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.16
    container_name: micro-kibana-video
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    networks:
      - app-network
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: micro-rabbitmq-video
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.docker/rabbitmqdata:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  ##rabbitmq_micro-video: #network criada no projeto com rabbitmq / COMPOSE DO RABBITMQ MOVIDO PARA ESTE ARQUIVO
    ##external: true COMPOSE DO RABBITMQ MOVIDO PARA ESTE ARQUIVO
